# Generated by Django 4.2.9 on 2024-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
