# Generated by Django 4.2.9 on 2024-03-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0002_alter_post_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
