# Generated by Django 4.2.9 on 2024-02-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0002_alter_post_content_alter_post_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
