# Generated by Django 4.2.9 on 2024-02-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0003_remove_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='STATUS',
        ),
    ]
