# Generated by Django 4.2.9 on 2024-02-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0004_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
