# Generated by Django 4.2.9 on 2024-03-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0004_remove_post_latitude_remove_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=32, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=32, max_digits=64, null=True),
        ),
    ]
