# Generated by Django 4.2.9 on 2024-02-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0005_remove_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
