# Generated by Django 4.2.9 on 2024-02-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0005_alter_post_options_alter_usercomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_2',
            field=models.CharField(default='Hello World!'),
        ),
        migrations.AddField(
            model_name='post',
            name='field_3',
            field=models.CharField(null=True),
        ),
    ]
