# Generated by Django 4.2.9 on 2024-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0006_post_field_2_post_field_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='STATUS',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
