# Generated by Django 4.2.9 on 2024-03-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0006_post_photo_reference_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_reference_timestamp',
        ),
    ]
