# Generated by Django 4.2.9 on 2024-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0011_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scottish_gems.region'),
            preserve_default=False,
        ),
    ]
