# Generated by Django 4.2.9 on 2024-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0015_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
