# Generated by Django 4.2.9 on 2024-02-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0017_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='google_place_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
