# Generated by Django 4.2.9 on 2024-02-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scottish_gems', '0018_post_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=1, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
